In [11]:
import pandas as pd

In [12]:
df = pd.read_excel(r"C:\Users\Dell\Desktop\Project\Amazon_Product_Review_Dataset.xlsx")

In [13]:
df.head(10)

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
0,P00001,Aditya Gupta,Desk Lamp 54,Sports,4484,3.0,3800,2025-07-03,1,5,4259.80,Net Banking,Mumbai
1,P00002,Priya Verma,Yoga Mat 399,Fashion,7796,4.4,2515,2025-12-15,4,15,26506.40,UPI,Kolkata
2,P00003,Nisha Joshi,Wireless Earbuds 131,Books,7724,4.9,1884,2025-11-02,2,30,10813.60,Debit Card,Bengaluru
3,P00004,Pooja Kumar,Wireless Earbuds 489,Electronics,1051,4.0,4517,2025-10-18,1,30,735.70,Credit Card,Delhi
4,P00005,Simran Mishra,Coffee Mug 157,Electronics,3883,3.7,2017,2025-06-30,2,15,6601.10,UPI,Bengaluru
5,P00006,Simran Joshi,Lunch Box 126,Electronics,1241,3.3,3846,2025-07-20,2,0,2482.00,Net Banking,Mumbai
6,P00007,Priya Sharma,Mouse 216,Electronics,7124,3.2,284,2025-09-22,5,20,28496.00,Debit Card,Patna
7,P00008,Nisha Kumar,Coffee Mug 51,Home & Kitchen,1457,4.8,4096,2025-02-27,1,0,1457.00,Net Banking,Ranchi
8,P00009,Kavya Joshi,Hair Dryer 185,Personal Care,4937,3.1,2484,2025-10-21,5,15,20982.25,Credit Card,Patna
9,P00010,Simran Singh,Wireless Earbuds 212,Furniture,1759,4.7,133,2025-08-09,4,5,6684.20,UPI,Patna

In [14]:
df.tail()

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
1995,P01996,Vikram Yadav,Bottle 137,Fashion,533,4.7,1020,2025-03-23,1,5,506.35,Net Banking,Patna
1996,P01997,Anjali Yadav,Keyboard 79,Furniture,5040,4.4,563,2025-02-02,1,15,4284.00,Credit Card,Ranchi
1997,P01998,Anjali Verma,Yoga Mat 315,Sports,5673,3.1,3305,2025-04-11,5,10,25528.50,Credit Card,Kolkata
1998,P01999,Anjali Joshi,Wireless Earbuds 166,Books,3934,4.1,1021,2025-01-17,3,10,10621.80,COD,Ranchi
1999,P02000,Rohan Sharma,Keyboard 288,Books,8493,4.8,3150,2025-05-12,1,20,6794.40,COD,Kolkata

In [15]:
df.shape

(2000, 13)

In [16]:
df.columns

Index(['Product_ID', 'Customer_Name', 'Product_Name', 'Category', 'Price',
       'Rating', 'Reviews_Count', 'Purchase_Date', 'Quantity', 'Discount (%)',
       'Final_Price', 'Payment_Method', 'City'],
      dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product_ID      2000 non-null   str
 1   Customer_Name   2000 non-null   str
 2   Product_Name    2000 non-null   str
 3   Category        2000 non-null   str
 4   Price           2000 non-null   int64
 5   Rating          2000 non-null   float64
 6   Reviews_Count   2000 non-null   int64
 7   Purchase_Date   2000 non-null   str
 8   Quantity        2000 non-null   int64
 9   Discount (%)    2000 non-null   int64
 10  Final_Price     2000 non-null   float64
 11  Payment_Method  2000 non-null   str
 12  City            2000 non-null   str
dtypes: float64(2), int64(4), str(7)
memory usage: 203.3 KB

In [18]:
df.dtypes

Product_ID            str
Customer_Name         str
Product_Name          str
Category              str
Price               int64
Rating            float64
Reviews_Count       int64
Purchase_Date         str
Quantity            int64
Discount (%)        int64
Final_Price       float64
Payment_Method        str
City                  str
dtype: object

In [19]:
df.describe()

,Price,Rating,Reviews_Count,Quantity,Discount (%),Final_Price
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,5085.129000,3.974900,2481.543000,2.988000,15.16000,12886.976800
std,2832.533143,0.575357,1455.985264,1.404223,9.96238,10065.373346
min,202.000000,3.000000,10.000000,1.000000,0.00000,162.000000
25%,2652.750000,3.500000,1216.500000,2.000000,5.00000,4975.675000
50%,5096.500000,3.900000,2414.500000,3.000000,15.00000,10163.550000
75%,7501.000000,4.500000,3762.500000,4.000000,25.00000,19020.262500
max,9996.000000,5.000000,4995.000000,5.000000,30.00000,49980.000000

In [20]:
df.isnull().sum()

Product_ID        0
Customer_Name     0
Product_Name      0
Category          0
Price             0
Rating            0
Reviews_Count     0
Purchase_Date     0
Quantity          0
Discount (%)      0
Final_Price       0
Payment_Method    0
City              0
dtype: int64

In [21]:
df.dropna()

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
0,P00001,Aditya Gupta,Desk Lamp 54,Sports,4484,3.0,3800,2025-07-03,1,5,4259.80,Net Banking,Mumbai
1,P00002,Priya Verma,Yoga Mat 399,Fashion,7796,4.4,2515,2025-12-15,4,15,26506.40,UPI,Kolkata
2,P00003,Nisha Joshi,Wireless Earbuds 131,Books,7724,4.9,1884,2025-11-02,2,30,10813.60,Debit Card,Bengaluru
3,P00004,Pooja Kumar,Wireless Earbuds 489,Electronics,1051,4.0,4517,2025-10-18,1,30,735.70,Credit Card,Delhi
4,P00005,Simran Mishra,Coffee Mug 157,Electronics,3883,3.7,2017,2025-06-30,2,15,6601.10,UPI,Bengaluru
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,P01996,Vikram Yadav,Bottle 137,Fashion,533,4.7,1020,2025-03-23,1,5,506.35,Net Banking,Patna
1996,P01997,Anjali Yadav,Keyboard 79,Furniture,5040,4.4,563,2025-02-02,1,15,4284.00,Credit Card,Ranchi
1997,P01998,Anjali Verma,Yoga Mat 315,Sports,5673,3.1,3305,2025-04-11,5,10,25528.50,Credit Card,Kolkata
1998,P01999,Anjali Joshi,Wireless Earbuds 166,Books,3934,4.1,1021,2025-01-17,3,10,10621.80,COD,Ranchi
1999,P02000,Rohan Sharma,Keyboard 288,Books,8493,4.8,3150,2025-05-12,1,20,6794.40,COD,Kolkata

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df = df.drop_duplicates()

In [24]:
df[["Customer_Name","City"]]

      Customer_Name       City
0      Aditya Gupta     Mumbai
1       Priya Verma    Kolkata
2       Nisha Joshi  Bengaluru
3       Pooja Kumar      Delhi
4     Simran Mishra  Bengaluru
...             ...        ...
1995   Vikram Yadav      Patna
1996   Anjali Yadav     Ranchi
1997   Anjali Verma    Kolkata
1998   Anjali Joshi     Ranchi
1999   Rohan Sharma    Kolkata

[2000 rows x 2 columns]

In [25]:
df.iloc[0]

Product_ID              P00001
Customer_Name     Aditya Gupta
Product_Name      Desk Lamp 54
Category                Sports
Price                     4484
Rating                     3.0
Reviews_Count             3800
Purchase_Date       2025-07-03
Quantity                     1
Discount (%)                 5
Final_Price             4259.8
Payment_Method     Net Banking
City                    Mumbai
Name: 0, dtype: object

In [27]:
df[df["Rating"] > 4]

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
1,P00002,Priya Verma,Yoga Mat 399,Fashion,7796,4.4,2515,2025-12-15,4,15,26506.40,UPI,Kolkata
2,P00003,Nisha Joshi,Wireless Earbuds 131,Books,7724,4.9,1884,2025-11-02,2,30,10813.60,Debit Card,Bengaluru
7,P00008,Nisha Kumar,Coffee Mug 51,Home & Kitchen,1457,4.8,4096,2025-02-27,1,0,1457.00,Net Banking,Ranchi
9,P00010,Simran Singh,Wireless Earbuds 212,Furniture,1759,4.7,133,2025-08-09,4,5,6684.20,UPI,Patna
10,P00011,Amit Kumar,Hair Dryer 183,Furniture,9453,4.9,4949,2025-05-05,1,5,8980.35,COD,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,P01995,Pooja Das,Keyboard 33,Books,6864,4.9,4569,2025-03-01,5,25,25740.00,UPI,Mumbai
1995,P01996,Vikram Yadav,Bottle 137,Fashion,533,4.7,1020,2025-03-23,1,5,506.35,Net Banking,Patna
1996,P01997,Anjali Yadav,Keyboard 79,Furniture,5040,4.4,563,2025-02-02,1,15,4284.00,Credit Card,Ranchi
1998,P01999,Anjali Joshi,Wireless Earbuds 166,Books,3934,4.1,1021,2025-01-17,3,10,10621.80,COD,Ranchi
1999,P02000,Rohan Sharma,Keyboard 288,Books,8493,4.8,3150,2025-05-12,1,20,6794.40,COD,Kolkata

In [28]:
df[(df["Rating"] > 4) & (df["Price"] < 1000)]

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
28,P00029,Vikram Mishra,Desk Lamp 367,Fashion,655,4.3,3313,2025-03-12,5,30,2292.50,Debit Card,Patna
37,P00038,Rohan Singh,Mouse 303,Sports,681,4.4,1875,2025-11-17,3,15,1736.55,COD,Bengaluru
41,P00042,Simran Sinha,Smart Watch 159,Sports,231,4.3,4737,2025-06-07,2,25,346.50,UPI,Bengaluru
54,P00055,Kavya Das,Charger 275,Sports,847,4.1,746,2025-04-15,1,0,847.00,COD,Mumbai
131,P00132,Vikram Kumar,Shoes 265,Furniture,909,4.8,3608,2025-03-22,5,25,3408.75,UPI,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906,P01907,Karan Gupta,Lunch Box 306,Fashion,380,4.7,4697,2025-03-20,3,0,1140.00,Debit Card,Kolkata
1962,P01963,Aditya Sinha,Shoes 252,Furniture,968,4.5,4519,2025-03-19,1,30,677.60,Credit Card,Kolkata
1970,P01971,Aditya Sharma,Backpack 222,Fashion,782,4.8,509,2025-11-11,1,0,782.00,Net Banking,Ranchi
1981,P01982,Pooja Patel,Charger 31,Fashion,264,4.8,1521,2025-08-02,1,25,198.00,COD,Bengaluru
1995,P01996,Vikram Yadav,Bottle 137,Fashion,533,4.7,1020,2025-03-23,1,5,506.35,Net Banking,Patna

In [29]:
len(df)

2000

In [31]:
df.sort_values("Price", ascending=False).head(5)

,Product_ID,Customer_Name,Product_Name,Category,Price,Rating,Reviews_Count,Purchase_Date,Quantity,Discount (%),Final_Price,Payment_Method,City
98,P00099,Karan Gupta,Wireless Earbuds 419,Fashion,9996,4.5,4026,2025-11-10,5,0,49980.0,Credit Card,Patna
633,P00634,Sneha Gupta,Coffee Mug 103,Electronics,9996,4.1,2684,2025-06-21,1,30,6997.2,Debit Card,Bengaluru
679,P00680,Aditya Sinha,Charger 441,Electronics,9994,3.3,3549,2025-02-03,1,10,8994.6,Debit Card,Delhi
120,P00121,Karan Gupta,Smart Watch 456,Personal Care,9991,3.7,415,2025-06-08,4,0,39964.0,Debit Card,Patna
474,P00475,Amit Sinha,Hair Dryer 396,Home & Kitchen,9986,4.0,2440,2025-06-27,4,10,35949.6,Debit Card,Patna